# Generated by Django 4.1.5 on 2023-02-25 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essivivi_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('qte_eaux', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essivivi_api.eau')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-created_at'],
            },
        ),
    ]
