# Generated by Django 4.1.5 on 2023-02-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essivivi_api', '0004_remove_agent_eau_agent_eau'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
