# Generated by Django 4.1.5 on 2023-03-10 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essivivi_api', '0007_client_remove_produit_user_eau_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eau',
            name='user',
        ),
        migrations.AddField(
            model_name='eau',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eaux', to=settings.AUTH_USER_MODEL),
        ),
    ]
