# Generated by Django 4.1.5 on 2023-03-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essivivi_api', '0010_rename_qtestock_usereau_qtestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
