# Generated by Django 4.1.5 on 2023-03-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essivivi_api', '0011_remove_produit_categorie_delete_cart_delete_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='eau',
            name='qteStock',
            field=models.IntegerField(null=True),
        ),
    ]
