# Generated by Django 4.1.5 on 2023-03-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essivivi_api', '0012_eau_qtestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='gerant_id',
            field=models.IntegerField(null=True),
        ),
    ]
