# Generated by Django 4.1.5 on 2023-03-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essivivi_api', '0014_alter_eau_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='nom_agent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='nom_produit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserEau',
        ),
    ]
