# Generated by Django 4.1.5 on 2023-03-18 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essivivi_api', '0015_agent_nom_agent_agent_nom_produit_delete_usereau'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essivivi_api.agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eauxRecue', to=settings.AUTH_USER_MODEL),
        ),
    ]
